#!/bin/zsh
VIM_DIR="${ZDOTDIR:-$HOME}/.vim"
PRESTO_DIR="${ZDOTDIR:-$HOME}/.zprezto"
RUN_DIR="${0:A:h}"

export VIM_DIR

mkdir -p $VIM_DIR/dein

git clone --recursive https://github.com/sorin-ionescu/prezto.git "$PRESTO_DIR"
setopt EXTENDED_GLOB
for rcfile in "$PRESTO_DIR"/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

rm "${ZDOTDIR:-$HOME}/.zpreztorc"

ln -s "$RUN_DIR"/zpreztorc "${ZDOTDIR:-$HOME}/.zpreztorc"

echo "export VIM_DIR=$VIM_DIR" >> "$PRESTO_DIR"/runcoms/zshrc

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > "$RUN_DIR"/installer.sh

sh "$RUN_DIR"/installer.sh "$VIM_DIR"/dein

ln -s "$RUN_DIR/vimrc" "${ZDOTDIR:-$HOME}/.vimrc"

vim

rm "$RUN_DIR"/installer.sh
