#!/bin/zsh
VIM_DIR="${ZDOTDIR:-$HOME}/.vim"
PRESTO_DIR="${ZDOTDIR:-$HOME}/.zprezto"
RUN_DIR="${0:A:h}"

mkdir -p $VIM_DIR/dein

git clone --recursive https://github.com/sorin-ionescu/prezto.git "$PRESTO_DIR"
setopt EXTENDED_GLOB
for rcfile in "$PRESTO_DIR"/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

cat "$RUN_DIR"/vimhead > "$RUN_DIR"/vimrc

echo "set runtimepath+=$VIM_DIR/dein/repos/github.com/Shougo/dein.vim" >> "$RUN_DIR"/vimrc
echo "call dein#begin('$VIM_DIR/dein')" >> "$RUN_DIR"/vimrc

cat "$RUN_DIR/vimtail" >> "$RUN_DIR"/vimrc

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > "$RUN_DIR"/installer.sh

sh "$RUN_DIR"/installer.sh "$VIM_DIR"/dein

ln -s "$RUN_DIR/vimrc" "${ZDOTDIR:-$HOME}/.vimrc"

vim

rm "$RUN_DIR"/installer.sh
